### ISSUE TITLE
Customer-facing ATM Endpoint

### ISSUE THREAD

**Issue by gwh59** [nessieisreal/nessie-python-sdk#2]
AC: A user of the Python SDK can use any API associated with the Customer-facing ATM endpoint. User will supply their own API key, and the SDK will utilize classes and objects (e.g. an ATM class) as a layer of abstraction so that even a lowly college freshman can feel comfortable using Nessie.  

We've decided to tackle this in an Object Oriented way, so look at the Android and Node SDKs for inspiration. Remember to use Python3 and not Python2. 

More info on the different APIs for the ATM Endpoint: http://api.reimaginebanking.com/documentation#!/ATM/

**Comment by SkyrmionJ** [comment]
Closing cause this has been merged
