### ISSUE TITLE
Customer-facing Customer Endpoint

### ISSUE THREAD

**Issue by gwh59** [nessieisreal/nessie-python-sdk#3]
AC: A user of the Python SDK can use any API associated with the Customer-facing Customer endpoint. User will supply their own API key, and the SDK will utilize classes and objects (e.g. an Customer class) as a layer of abstraction so that even a lowly college freshman can feel comfortable using Nessie.  

We've decided to tackle this in an Object Oriented way, so look at the Android and Node SDKs for inspiration. Remember to use Python3 and not Python2. 

More info on the different APIs for the Customer Endpoint: http://api.reimaginebanking.com/documentation#!/Customer/

**Comment by SkyrmionJ** [comment]
Working on Customer 
Can't assign myself nor actually push to this repo :/

> ERROR: Permission to nessieisreal/nessie-python-sdk.git denied to SkyrmionJ.
> fatal: Could not read from remote repository.
> 
>Please make sure you have the correct access rights
>and the repository exists.

**Comment by maggie9595** [comment]
Oops just realized George made this repo, but I gave you write access @SkyrmionJ

**Comment by maggie9595** [comment]
I can't seem to assign you either though, maybe @gwh59 can?

**Comment by maggie9595** [comment]
@gwh59 I gave everyone on the Nessie developers team read access to this repo so hope that's ok, but I think you'll have to add other people you want to have push access manually/let everyone on the team have access if you want.

**Comment by SkyrmionJ** [comment]
Thanks!

**Comment by gwh59** [comment]
@maggie9595 that's fine - thanks!
